name: Python checks

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

permissions: read-all

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.11'
          - '3.12'
          - '3.13'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        resolution:
          - highest

    permissions:
      contents: write

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - uses: install-pinned/uv@e29cd923c49146a4fcc66eb0c8bea117e33ed9ce

      - run: |
          uv pip install --system --resolution ${{ matrix.resolution }} -e .[dev]

      - id: cache-pytest
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: .pytest_cache
          key: pytest-${{ matrix.python-version }}-${{ matrix.os }}-${{ matrix.resolution }}-${{ hashFiles('pyproject.toml') }}

      - run: pytest
        env:
          COVERAGE_FILE: ".coverage.${{ matrix.os }}.${{ matrix.python-version }}.${{ matrix.resolution }}"

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.resolution }}
          path: .coverage.${{ matrix.os }}.${{ matrix.python-version }}.${{ matrix.resolution }}
          include-hidden-files: true

  ruff-format:
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.13
          cache: pip

      - uses: install-pinned/uv@a1c8d54c22711715919a4c208689ed99f0eba797

      - run: uv pip install --system .[dev]

      - id: cache-ruff
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .ruff_cache
          key: ruff-${{ hashFiles('pyproject.toml') }}

      - id: run-ruff
        run: ruff format --diff .

  ruff-check:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.13
          cache: pip

      - uses: install-pinned/uv@a1c8d54c22711715919a4c208689ed99f0eba797

      - run: uv pip install --system .[dev]

      - id: cache-ruff
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .ruff_cache
          key: ruff-${{ hashFiles('pyproject.toml') }}

      - id: run-ruff-sarif
        run: |
          ruff check --output-format=sarif -o results.sarif .

      - uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3
        if: ( success() || failure() ) && contains('["success", "failure"]', steps.run-ruff-sarif.outcome)
        with:
          sarif_file: results.sarif

      - id: run-ruff
        if: failure() && contains('["failure"]', steps.run-ruff-sarif.outcome)
        run: |
          ruff check --output-format=github .

  bandit:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.13
          cache: pip

      - uses: install-pinned/uv@a1c8d54c22711715919a4c208689ed99f0eba797

      - run: uv pip install --system .[dev]

      - id: run-bandit-sarif
        run: |
          bandit --confidence-level 'medium' --severity-level 'medium' --recursive 'src' --format 'sarif' --output 'results.sarif'

      - uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3
        if: ( success() || failure() ) && contains('["success", "failure"]', steps.run-bandit-sarif.outcome)
        with:
          sarif_file: results.sarif

      - id: run-bandit
        if: failure() && contains('["failure"]', steps.run-bandit-sarif.outcome)
        run: |
          bandit --confidence-level 'medium' --severity-level 'medium' --recursive 'src'

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.13'
          cache: pip

      - uses: install-pinned/uv@a1c8d54c22711715919a4c208689ed99f0eba797

      - run: uv pip install --system -e .[dev]

      - id: cache-mypy
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('pyproject.toml') }}

      - run: mypy .

  coverage:
    runs-on: ubuntu-latest
    needs: pytest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            img.shields.io:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
        with:
          pattern: coverage-*
          merge-multiple: true

      - id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@91aaf3b39c7e2331c6bc77767ce017f5160c5f11
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_COVERAGE_FILES: true

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt

  pre-commit:
    runs-on: ubuntu-latest
    needs:
      - ruff-format
      - ruff-check
      - bandit

    permissions:
      contents: write

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            proxy.golang.org:443
            pypi.org:443

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.13
          cache: pip

      - uses: install-pinned/uv@a1c8d54c22711715919a4c208689ed99f0eba797

      - run: uv pip install --system .[dev]

      - id: cache-pre-commit
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .pre-commit-cache
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('pyproject.toml') }}

      - run: |
          pre-commit install
          pre-commit run --all-files
        env:
          PRE_COMMIT_HOME: .pre-commit-cache
